spring:
  application:
    name: feign
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#全局超时连接配置,feign默认配置ribbon
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000

#单个微服务超时连接设置 
item-service:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

#feign默认关闭hystrix    
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream 
    
    
    
    
    
    
    
    
    
    
    
    
    